services:
  app:
    build: .
    container_name: api-flask
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/school_db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_DATABASE=school_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"

volumes:
  mysql_data:
